name: Bug Report
description: File a bug report.
assignees: ["smordarski", "gmordarski"]
labels: ["bug"]
title: "[Bug Report]: "
body:
  - type: markdown
    attributes:
      value: "File a bug report."
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: Check this box if you have read our Code of Conduct.
          required: true
        - label: Make sure you have looked for other issues in our repository before posting this issue.
          required: true
  - type: textarea
    attributes:
      label: Description
      description: "Describe the bug."
      value: |
        Enter information about the bug here.
    validations:
      required: true
