blank_issues_enabled: false
contact_links:
  - name: Mordarski Networks Community Support
    url: https://github.com/orgs/Mordarski-Networks/discussions
    about: Please ask and answer questions here.
