name: Lint

on:
  push:
    paths: "scripts/**"
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: psf/black@721dff549362f54930ecc038218dcc40e599a875
