name: Replace

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy hosts/hosts.txt to hosts/zero/hosts.txt
        run: cp hosts/hosts.txt hosts/zero/hosts.txt

      - name: Replace 127.0.0.1 with 0.0.0.0
        run: sed -i 's/127\.0\.0\.1/0\.0\.0\.0/g' hosts/zero/hosts.txt

      - name: Commit changes
        run: |
          date > generated.txt
          git config --global user.email github-actions
          git config --global user.name github-actions@github.com
          git add .
          git commit -a -S -m "Copy and modify hosts file"
          git push origin main
