name: Replace

permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Copy hosts/hosts.txt to hosts/zero/hosts.txt
        run: cp hosts/hosts.txt hosts/zero/hosts.txt

      - name: Replace 127.0.0.1 with 0.0.0.0
        run: sed -i -b 's/127\.0\.0\.1/0\.0\.0\.0/g' hosts/zero/hosts.txt

      - name: Commit changes
        run: |
          git add .
          git commit -S -m "Copy and modify hosts file"
          git push
